#!/usr/bin/env bash


rebuild_pkg()
{
    filepath=$1

    cd $build_dir
    base=$(echo $filepath | rev | cut -d '/' -f 1 | rev)
    echo "Downloading PKGBUILD for <$base>"
    $(python ../get_pkgbuild_files.py $base 2&>>error.log)

    $(makepkg -is --noconfirm 2&>>error.log)

    $(sudo rm -r *)
    cd ..

    create_debug_file $filepath
}

create_debug_file()
{
    exepath=$1
    debugfile=$(echo $exepath | rev | cut -d '/' -f 1 | rev)

    debugfile=$debugfile.debug

    echo "creating debug file for $exepath [$debugfile]"
    $(objcopy --only-keep-debug $exepath $debugfile)
    echo "Stripping $exepath...."
    $(sudo strip --strip-all $exepath)
    echo "adding gnu-debuglink $debugfile"
    $(sudo objcopy --add-gnu-debuglink=$debugfile $exepath)
    $(sudo mv $debugfile $debug_dir) 
}

parse_file()
{
    filepath=$1

    file_output=$(file $filepath)

    if [[ $file_output =~ "with debug" ]]
    then
        echo "<$filepath>....is *not* stripped"
        create_debug_file $filepath
    elif [[ $file_output =~ "stripped" ]]
    then
        echo "<$filepath>....is stripped"
        rebuild_pkg $filepath
    else
        echo "<$filepath>....is not a binary\n"
    fi
}

is_path_or_file()
{

	link=$1
	if [[ $link =~ "/" ]]
	then
		echo Following symlink...$link
		check_pkg_path $link;
	else
		echo Following symlink.../usr/bin/$link
		check_pkg_file $link;
	fi
}

check_pkg_path()
{
	pkg_path=$1

	if [[ -x $pkg_path ]]
	then
		parse_file $pkg_path;
	fi
}

check_pkg_file()
{
	pkg=$1
	# add check on posix script files
    if [[ -h /usr/bin/$pkg ]]
    then
        exepath=$(readlink /usr/bin/$pkg);
        is_path_or_file $exepath;
    elif [[ -x /usr/bin/$pkg ]]
    then
        parse_file "/usr/bin/$pkg";
    elif [[ ! -f /usr/bin/$pkg ]]
    then
        echo Invalid filename
        exit 1
    fi
}

pac_query()
{
	echo "[[ Initializing pacman package database query.... ]]";

	for pkg in $(pacman -Qnq)
	do
		if [[ -a /usr/bin/$pkg ]]
		then
			echo "[Package :: <$pkg>]";
			echo "Checking pkg binary...";
			check_pkg_file $pkg;
		fi
	done

	echo "[[ Query complete ]]";
}

build_dir="build_dir"

if [[ ! -d $build_dir ]]
then
    $(mkdir $build_dir)
fi

debug_dir="/usr/bin/.debug"

if [[ ! -d $debug_dir ]]
then
    $(sudo mkdir $debug_dir)
fi


while getopts "ap:" opts
do
    case $opts in

    a)
        pac_query
        ;;
    p)
        check_pkg_file $OPTARG
        ;;
    ?)
        echo Invalid Option
        exit 1
    esac
done

if [[ -d $build_dir ]]
then
    $(rm -r $build_dir)
fi

